In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("./data/students.csv")
df.head()

   student_id first_name last_name  age gender
0           1       Emma   Johnson   20      F
1           2       Liam     Smith   22      M
2           3     Olivia  Williams   19      F
3           4       Noah     Brown   21      M
4           5        Ava     Jones   20      F

In [4]:
df["email"] = (df.first_name + df.last_name + "@gmail.com").str.strip().str.lower()

df.head()

   student_id first_name last_name  age gender                     email
0           1       Emma   Johnson   20      F     emmajohnson@gmail.com
1           2       Liam     Smith   22      M       liamsmith@gmail.com
2           3     Olivia  Williams   19      F  oliviawilliams@gmail.com
3           4       Noah     Brown   21      M       noahbrown@gmail.com
4           5        Ava     Jones   20      F        avajones@gmail.com

In [13]:
initials = []
for i in df.first_name.values:
    initials.append(i[0])

username = pd.Series(initials) + df.last_name
df["username"] = username
df

,student_id,first_name,last_name,age,gender,email,username
0,1,Emma,Johnson,20,F,emmajohnson@gmail.com,EJohnson
1,2,Liam,Smith,22,M,liamsmith@gmail.com,LSmith
2,3,Olivia,Williams,19,F,oliviawilliams@gmail.com,OWilliams
3,4,Noah,Brown,21,M,noahbrown@gmail.com,NBrown
4,5,Ava,Jones,20,F,avajones@gmail.com,AJones
5,6,Elijah,Miller,23,M,elijahmiller@gmail.com,EMiller
6,7,Sophia,Davis,18,F,sophiadavis@gmail.com,SDavis
7,8,James,Garcia,22,M,jamesgarcia@gmail.com,JGarcia
8,9,Isabella,Martinez,20,F,isabellamartinez@gmail.com,IMartinez
9,10,Lucas,Wilson,21,M,lucaswilson@gmail.com,LWilson
10,11,Mia,Anderson,19,F,miaanderson@gmail.com,MAnderson
11,12,Mason,Thomas,22,M,masonthomas@gmail.com,MThomas
12,13,Amelia,Taylor,20,F,ameliataylor@gmail.com,ATaylor
13,14,Ethan,Moore,23,M,ethanmoore@gmail.com,EMoore
14,15,Harper,Jackson,19,F,harperjackson@gmail.com,HJackson
15,16,Logan,Martin,21,M,loganmartin@gmail.com,LMartin
16,17,Evelyn,Lee,20,F,evelynlee@gmail.com,ELee
17,18,Benjamin,Perez,22,M,benjaminperez@gmail.com,BPerez
18,19,Abigail,Thompson,19,F,abigailthompson@gmail.com,AThompson
19,20,Oliver,White,21,M,oliverwhite@gmail.com,OWhite
20,21,Charlotte,Harris,20,F,charlotteharris@gmail.com,CHarris
21,22,Jacob,Sanchez,23,M,jacobsanchez@gmail.com,JSanchez
22,23,Emily,Clark,18,F,emilyclark@gmail.com,EClark
23,24,Michael,Ramirez,22,M,michaelramirez@gmail.com,MRamirez
24,25,Elizabeth,Lewis,19,F,elizabethlewis@gmail.com,ELewis
25,26,Alexander,Robinson,21,M,alexanderrobinson@gmail.com,ARobinson
26,27,Sofia,Walker,20,F,sofiawalker@gmail.com,SWalker
27,28,Daniel,Young,22,M,danielyoung@gmail.com,DYoung
28,29,Avery,Allen,19,F,averyallen@gmail.com,AAllen
29,30,Matthew,King,21,M,matthewking@gmail.com,MKing
30,31,Scarlett,Wright,20,F,scarlettwright@gmail.com,SWright
31,32,Joseph,Scott,23,M,josephscott@gmail.com,JScott
32,33,Ella,Torres,18,F,ellatorres@gmail.com,ETorres
33,34,David,Nelson,22,M,davidnelson@gmail.com,DNelson
34,35,Grace,Hill,19,F,gracehill@gmail.com,GHill
35,36,Samuel,Green,21,M,samuelgreen@gmail.com,SGreen
36,37,Chloe,Adams,20,F,chloeadams@gmail.com,CAdams
37,38,Henry,Baker,22,M,henrybaker@gmail.com,HBaker
38,39,Lily,Gonzalez,19,F,lilygonzalez@gmail.com,LGonzalez
39,40,Jackson,Nelson,21,M,jacksonnelson@gmail.com,JNelson
40,41,Zoe,Carter,20,F,zoecarter@gmail.com,ZCarter
41,42,Aiden,Morris,23,M,aidenmorris@gmail.com,AMorris
42,43,Hannah,Rogers,18,F,hannahrogers@gmail.com,HRogers
43,44,Wyatt,Reed,22,M,wyattreed@gmail.com,WReed
44,45,Natalie,Cook,19,F,nataliecook@gmail.com,NCook
45,46,Owen,Morgan,21,M,owenmorgan@gmail.com,OMorgan
46,47,Lillian,Bell,20,F,lillianbell@gmail.com,LBell
47,48,Gabriel,Murphy,22,M,gabrielmurphy@gmail.com,GMurphy
48,49,Aria,Bailey,19,F,ariabailey@gmail.com,ABailey
49,50,Carter,Rivera,21,M,carterrivera@gmail.com,CRivera

In [22]:
df["password"] = (df.last_name + "pass" ).str.strip()

df.head()

,student_id,first_name,last_name,age,gender,email,password
0,1,Emma,Johnson,20,F,emmajohnson@gmail.com,Johnsonpass
1,2,Liam,Smith,22,M,liamsmith@gmail.com,Smithpass
2,3,Olivia,Williams,19,F,oliviawilliams@gmail.com,Williamspass
3,4,Noah,Brown,21,M,noahbrown@gmail.com,Brownpass
4,5,Ava,Jones,20,F,avajones@gmail.com,Jonespass

In [30]:
cred = df[["student_id", "email", "password"]].set_index('student_id')
cred.head()

                               email      password
student_id
1              emmajohnson@gmail.com   Johnsonpass
2                liamsmith@gmail.com     Smithpass
3           oliviawilliams@gmail.com  Williamspass
4                noahbrown@gmail.com     Brownpass
5                 avajones@gmail.com     Jonespass

In [15]:
df.to_csv("./data/students.csv", mode="w")

In [16]:
pd.read_csv("./data/students.csv")

,Unnamed: 0,student_id,first_name,last_name,age,gender,email,username
0,0,1,Emma,Johnson,20,F,emmajohnson@gmail.com,EJohnson
1,1,2,Liam,Smith,22,M,liamsmith@gmail.com,LSmith
2,2,3,Olivia,Williams,19,F,oliviawilliams@gmail.com,OWilliams
3,3,4,Noah,Brown,21,M,noahbrown@gmail.com,NBrown
4,4,5,Ava,Jones,20,F,avajones@gmail.com,AJones
5,5,6,Elijah,Miller,23,M,elijahmiller@gmail.com,EMiller
6,6,7,Sophia,Davis,18,F,sophiadavis@gmail.com,SDavis
7,7,8,James,Garcia,22,M,jamesgarcia@gmail.com,JGarcia
8,8,9,Isabella,Martinez,20,F,isabellamartinez@gmail.com,IMartinez
9,9,10,Lucas,Wilson,21,M,lucaswilson@gmail.com,LWilson
10,10,11,Mia,Anderson,19,F,miaanderson@gmail.com,MAnderson
11,11,12,Mason,Thomas,22,M,masonthomas@gmail.com,MThomas
12,12,13,Amelia,Taylor,20,F,ameliataylor@gmail.com,ATaylor
13,13,14,Ethan,Moore,23,M,ethanmoore@gmail.com,EMoore
14,14,15,Harper,Jackson,19,F,harperjackson@gmail.com,HJackson
15,15,16,Logan,Martin,21,M,loganmartin@gmail.com,LMartin
16,16,17,Evelyn,Lee,20,F,evelynlee@gmail.com,ELee
17,17,18,Benjamin,Perez,22,M,benjaminperez@gmail.com,BPerez
18,18,19,Abigail,Thompson,19,F,abigailthompson@gmail.com,AThompson
19,19,20,Oliver,White,21,M,oliverwhite@gmail.com,OWhite
20,20,21,Charlotte,Harris,20,F,charlotteharris@gmail.com,CHarris
21,21,22,Jacob,Sanchez,23,M,jacobsanchez@gmail.com,JSanchez
22,22,23,Emily,Clark,18,F,emilyclark@gmail.com,EClark
23,23,24,Michael,Ramirez,22,M,michaelramirez@gmail.com,MRamirez
24,24,25,Elizabeth,Lewis,19,F,elizabethlewis@gmail.com,ELewis
25,25,26,Alexander,Robinson,21,M,alexanderrobinson@gmail.com,ARobinson
26,26,27,Sofia,Walker,20,F,sofiawalker@gmail.com,SWalker
27,27,28,Daniel,Young,22,M,danielyoung@gmail.com,DYoung
28,28,29,Avery,Allen,19,F,averyallen@gmail.com,AAllen
29,29,30,Matthew,King,21,M,matthewking@gmail.com,MKing
30,30,31,Scarlett,Wright,20,F,scarlettwright@gmail.com,SWright
31,31,32,Joseph,Scott,23,M,josephscott@gmail.com,JScott
32,32,33,Ella,Torres,18,F,ellatorres@gmail.com,ETorres
33,33,34,David,Nelson,22,M,davidnelson@gmail.com,DNelson
34,34,35,Grace,Hill,19,F,gracehill@gmail.com,GHill
35,35,36,Samuel,Green,21,M,samuelgreen@gmail.com,SGreen
36,36,37,Chloe,Adams,20,F,chloeadams@gmail.com,CAdams
37,37,38,Henry,Baker,22,M,henrybaker@gmail.com,HBaker
38,38,39,Lily,Gonzalez,19,F,lilygonzalez@gmail.com,LGonzalez
39,39,40,Jackson,Nelson,21,M,jacksonnelson@gmail.com,JNelson
40,40,41,Zoe,Carter,20,F,zoecarter@gmail.com,ZCarter
41,41,42,Aiden,Morris,23,M,aidenmorris@gmail.com,AMorris
42,42,43,Hannah,Rogers,18,F,hannahrogers@gmail.com,HRogers
43,43,44,Wyatt,Reed,22,M,wyattreed@gmail.com,WReed
44,44,45,Natalie,Cook,19,F,nataliecook@gmail.com,NCook
45,45,46,Owen,Morgan,21,M,owenmorgan@gmail.com,OMorgan
46,46,47,Lillian,Bell,20,F,lillianbell@gmail.com,LBell
47,47,48,Gabriel,Murphy,22,M,gabrielmurphy@gmail.com,GMurphy
48,48,49,Aria,Bailey,19,F,ariabailey@gmail.com,ABailey
49,49,50,Carter,Rivera,21,M,carterrivera@gmail.com,CRivera